spring:
  application:
    name: academic-events-api

  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/academic_events_db
    username: ups
    password: ups123
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379
      password: Redis_Local_2026!

  jackson:
    time-zone: UTC

server:
  port: 8080
  servlet:
    context-path: /api

app:
  timezone:
    business: America/Guayaquil

jwt:
  secret: ${JWT_SECRET:cambia-este-secreto-en-produccion-por-uno-largo-y-seguro}
  access-expiration: ${JWT_ACCESS_EXPIRATION:900000}      # 15 minutos en ms
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000} # 7 d\u00edas en ms

cors:
  allowed-origins: ${ALLOWED_ORIGINS:http://localhost:5173,http://localhost:3000}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never